// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhqv52V-C5eU5x-v-6NSOhvfaB2uqHs4k',
    appId: '1:317027260871:web:bc8f0035a24c48dafee1e2',
    messagingSenderId: '317027260871',
    projectId: 'mainn-1fbea',
    authDomain: 'mainn-1fbea.firebaseapp.com',
    storageBucket: 'mainn-1fbea.appspot.com',
    measurementId: 'G-RZ1PHSC6SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPhImkw-BVu1XXCn3BcLv5VYLmvGKY5IE',
    appId: '1:317027260871:android:369be9a2673787abfee1e2',
    messagingSenderId: '317027260871',
    projectId: 'mainn-1fbea',
    storageBucket: 'mainn-1fbea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBexKZtPtcEFtpwXNP0hdzPuU9ToO4XTXg',
    appId: '1:317027260871:ios:ba2a820643fd5d98fee1e2',
    messagingSenderId: '317027260871',
    projectId: 'mainn-1fbea',
    storageBucket: 'mainn-1fbea.appspot.com',
    iosBundleId: 'com.example.mainn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBexKZtPtcEFtpwXNP0hdzPuU9ToO4XTXg',
    appId: '1:317027260871:ios:ba2a820643fd5d98fee1e2',
    messagingSenderId: '317027260871',
    projectId: 'mainn-1fbea',
    storageBucket: 'mainn-1fbea.appspot.com',
    iosBundleId: 'com.example.mainn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhqv52V-C5eU5x-v-6NSOhvfaB2uqHs4k',
    appId: '1:317027260871:web:00ded812eba2986efee1e2',
    messagingSenderId: '317027260871',
    projectId: 'mainn-1fbea',
    authDomain: 'mainn-1fbea.firebaseapp.com',
    storageBucket: 'mainn-1fbea.appspot.com',
    measurementId: 'G-ZBWS7386Q2',
  );
}
